### PR TITLE
chore(config): better naming for settlement config

### LINKED ISSUE #493: `node_address` in dymint.toml is confusing
the `node_address` in dymint.toml refers to the settlement node address, however it isn't prefixed with a `settlement` or with a comment suggesting it.

it caused rollapp users accidently to put their the sequencer address.

### PR DESCRIPTION
**Pull request by mtsitrin**
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Close #493 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

**Review by danwt — APPROVED** [review]
lgtm

**Review by srene — COMMENTED** [review]
shouldn't we also add the settlement prefix to the retry params to be consistent?

**Comment by mtsitrin** [comment]
> shouldn't we also add the settlement prefix to the retry params to be consistent?

I thought about changing only the "confusing" fields

**Comment by danwt** [comment]
just an idea maybe we can use a toml lib to write this in future instead of a template
https://pkg.go.dev/github.com/BurntSushi/toml#section-readme
might be hard to add comments though

**Pull request merged**
