### PR TITLE
fix(celestia): use fixed delay in repeat attempts

### PR DESCRIPTION
**Pull request by danwt**
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Close https://github.com/dymensionxyz/dymint/issues/752

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

**Review by srene — COMMENTED** [review]
IMO, its better to keep the backoff function, since there is a min and max delay. In case both values are the same, the delay will be fixed and will not increase over time. What i think we need is to be able to set those values in the config file, so nodes can choose the behavior, fixed or increasing delay,  in case problems with batch submissions.

**Comment by danwt** [comment]
ok I will add another pr to expose config

**Comment by danwt** [comment]
you can still merge this?

**Comment by danwt** [comment]
see https://github.com/dymensionxyz/dymint/pull/757 for exposing config

**Review by zale144 — APPROVED** [review]

**Review by mtsitrin — APPROVED** [review]

**Review by zale144 — APPROVED** [review]

**Pull request merged**
